CREATE TABLE IF NOT EXISTS geo_sites (
  site_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '站点主键 ID',
  domain VARCHAR(255) NOT NULL COMMENT '注册域名，如 example.com',
  site_root_url VARCHAR(512) NOT NULL COMMENT '站点根 URL（scheme + host）',
  scope_root_url VARCHAR(512) NOT NULL COMMENT '抓取作用域根 URL，可能包含语言路径前缀',
  scope_key CHAR(64) NOT NULL COMMENT '域名与作用域组合后的稳定哈希键',
  business_type VARCHAR(64) DEFAULT NULL COMMENT '推断的业务类型，如 saas、ecommerce',
  total_url_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前站点已登记的有效 URL 数量',
  snapshot_url_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前站点已保存页面快照的 URL 数量',
  discovery_json LONGTEXT DEFAULT NULL COMMENT '最新一次 discovery 结果的完整 JSON',
  key_pages_json JSON DEFAULT NULL COMMENT '识别出的关键页面集合 JSON',
  last_discovered_at DATETIME(6) DEFAULT NULL COMMENT '最近一次 discovery 完成时间',
  last_snapshot_at DATETIME(6) DEFAULT NULL COMMENT '最近一次页面快照写入时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
  PRIMARY KEY (site_id),
  UNIQUE KEY uq_geo_sites_domain_scope (domain, scope_key),
  KEY idx_geo_sites_last_discovered (last_discovered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点资产主表，记录站点作用域、快照与 discovery 聚合信息';

CREATE TABLE IF NOT EXISTS geo_urls (
  url_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'URL 主键 ID',
  site_id BIGINT UNSIGNED NOT NULL COMMENT '所属站点 ID',
  normalized_url VARCHAR(1024) NOT NULL COMMENT '规范化后的 URL',
  url_hash CHAR(64) NOT NULL COMMENT '规范化 URL 的稳定哈希值',
  final_url VARCHAR(1024) DEFAULT NULL COMMENT '抓取后的最终 URL',
  url_type VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT 'URL 分类，如 homepage、product、docs',
  discovery_source VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT 'URL 来源，如 entry、sitemap、internal_link',
  priority SMALLINT NOT NULL DEFAULT 0 COMMENT '后续抓取与排序优先级，值越小越优先',
  fetch_status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'URL 抓取状态，如 pending、success、error、stale',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否仍视为站点有效 URL',
  last_discovered_at DATETIME(6) DEFAULT NULL COMMENT '最近一次被发现时间',
  last_fetched_at DATETIME(6) DEFAULT NULL COMMENT '最近一次完成抓取时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
  PRIMARY KEY (url_id),
  UNIQUE KEY uq_geo_urls_site_hash (site_id, url_hash),
  KEY idx_geo_urls_site_type (site_id, url_type),
  KEY idx_geo_urls_site_source (site_id, discovery_source),
  KEY idx_geo_urls_site_priority (site_id, priority),
  CONSTRAINT fk_geo_urls_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点 URL 清单表，记录规范化 URL、分类与抓取状态';

CREATE TABLE IF NOT EXISTS geo_page_snapshots (
  snapshot_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '页面快照主键 ID',
  site_id BIGINT UNSIGNED NOT NULL COMMENT '所属站点 ID',
  url_id BIGINT UNSIGNED NOT NULL COMMENT '对应的 URL 记录 ID',
  normalized_url VARCHAR(1024) NOT NULL COMMENT '抓取入口 URL 的规范化结果',
  final_url VARCHAR(1024) NOT NULL COMMENT '实际抓取后的最终 URL',
  url_type VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT '页面类型分类，如 homepage、product、docs',
  fetch_status VARCHAR(32) NOT NULL DEFAULT 'success' COMMENT '本次快照抓取状态',
  status_code INT DEFAULT NULL COMMENT '页面抓取的 HTTP 状态码',
  title VARCHAR(512) DEFAULT NULL COMMENT '页面标题',
  meta_description TEXT DEFAULT NULL COMMENT '页面 meta description',
  canonical VARCHAR(1024) DEFAULT NULL COMMENT '页面 canonical URL',
  lang VARCHAR(32) DEFAULT NULL COMMENT '页面 lang 声明',
  word_count INT NOT NULL DEFAULT 0 COMMENT '页面词数统计',
  html_length INT NOT NULL DEFAULT 0 COMMENT 'HTML 长度统计',
  text_excerpt TEXT DEFAULT NULL COMMENT '页面正文摘要',
  content_hash CHAR(64) DEFAULT NULL COMMENT '正文或快照内容的稳定哈希值',
  page_profile_json LONGTEXT NOT NULL COMMENT 'PageProfile 序列化 JSON',
  parsed_json LONGTEXT DEFAULT NULL COMMENT 'HTML 解析结果 JSON',
  text_content MEDIUMTEXT DEFAULT NULL COMMENT '页面正文纯文本',
  raw_html MEDIUMTEXT DEFAULT NULL COMMENT '原始 HTML，可按配置关闭存储',
  fetched_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '快照抓取时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '快照更新时间',
  PRIMARY KEY (snapshot_id),
  UNIQUE KEY uq_geo_page_snapshots_url (url_id),
  KEY idx_geo_page_snapshots_site (site_id),
  KEY idx_geo_page_snapshots_type (site_id, url_type),
  KEY idx_geo_page_snapshots_fetched_at (fetched_at),
  CONSTRAINT fk_geo_page_snapshots_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_page_snapshots_url FOREIGN KEY (url_id) REFERENCES geo_urls (url_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='页面快照表，保存页面画像、解析结果与抓取元数据';

CREATE TABLE IF NOT EXISTS geo_graph_entities (
  entity_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图谱实体主键 ID',
  site_id BIGINT UNSIGNED NOT NULL COMMENT '所属站点 ID',
  entity_key CHAR(64) NOT NULL COMMENT '实体稳定键，基于类型与规范标识哈希生成',
  entity_type VARCHAR(64) NOT NULL COMMENT '实体类型，如 site、page、organization、product',
  canonical_name VARCHAR(512) DEFAULT NULL COMMENT '实体规范名称',
  canonical_url VARCHAR(1024) DEFAULT NULL COMMENT '实体规范 URL（如果存在）',
  source_snapshot_id BIGINT UNSIGNED DEFAULT NULL COMMENT '首次抽取该实体的页面快照 ID',
  confidence DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '实体抽取置信度，范围 0-100',
  attributes_json LONGTEXT DEFAULT NULL COMMENT '实体扩展属性 JSON',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
  PRIMARY KEY (entity_id),
  UNIQUE KEY uq_geo_graph_entities_site_key (site_id, entity_key),
  KEY idx_geo_graph_entities_site_type (site_id, entity_type),
  KEY idx_geo_graph_entities_site_url (site_id, canonical_url(255)),
  CONSTRAINT fk_geo_graph_entities_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_graph_entities_snapshot FOREIGN KEY (source_snapshot_id) REFERENCES geo_page_snapshots (snapshot_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点知识图谱实体投影表';

CREATE TABLE IF NOT EXISTS geo_graph_edges (
  edge_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图谱关系边主键 ID',
  site_id BIGINT UNSIGNED NOT NULL COMMENT '所属站点 ID',
  edge_key CHAR(64) NOT NULL COMMENT '关系边稳定键，基于起点、终点和关系类型哈希生成',
  from_entity_id BIGINT UNSIGNED NOT NULL COMMENT '起点实体 ID',
  to_entity_id BIGINT UNSIGNED NOT NULL COMMENT '终点实体 ID',
  relation_type VARCHAR(64) NOT NULL COMMENT '关系类型，如 has_page、links_to、same_as、offers',
  confidence DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '关系抽取置信度，范围 0-100',
  evidence_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联证据条数',
  attributes_json LONGTEXT DEFAULT NULL COMMENT '关系扩展属性 JSON',
  first_seen_at DATETIME(6) DEFAULT NULL COMMENT '首次观察到该关系的时间',
  last_seen_at DATETIME(6) DEFAULT NULL COMMENT '最近一次观察到该关系的时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
  PRIMARY KEY (edge_id),
  UNIQUE KEY uq_geo_graph_edges_site_key (site_id, edge_key),
  KEY idx_geo_graph_edges_site_relation (site_id, relation_type),
  KEY idx_geo_graph_edges_from (from_entity_id),
  KEY idx_geo_graph_edges_to (to_entity_id),
  CONSTRAINT fk_geo_graph_edges_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_graph_edges_from_entity FOREIGN KEY (from_entity_id) REFERENCES geo_graph_entities (entity_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_graph_edges_to_entity FOREIGN KEY (to_entity_id) REFERENCES geo_graph_entities (entity_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点知识图谱关系边投影表';

CREATE TABLE IF NOT EXISTS geo_graph_evidence (
  evidence_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图谱证据主键 ID',
  site_id BIGINT UNSIGNED NOT NULL COMMENT '所属站点 ID',
  entity_id BIGINT UNSIGNED DEFAULT NULL COMMENT '关联的实体 ID，可为空',
  edge_id BIGINT UNSIGNED DEFAULT NULL COMMENT '关联的关系边 ID，可为空',
  snapshot_id BIGINT UNSIGNED DEFAULT NULL COMMENT '证据来源的页面快照 ID',
  url_id BIGINT UNSIGNED DEFAULT NULL COMMENT '证据来源的 URL 记录 ID',
  evidence_type VARCHAR(32) NOT NULL COMMENT '证据类型，如 json_ld、anchor、heuristic、inventory',
  evidence_field VARCHAR(128) DEFAULT NULL COMMENT '证据字段名，如 sameAs、internal_links',
  selector_or_path VARCHAR(255) DEFAULT NULL COMMENT '证据定位路径或逻辑位置',
  evidence_text TEXT DEFAULT NULL COMMENT '证据文本或摘要',
  confidence DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '证据抽取置信度，范围 0-100',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  PRIMARY KEY (evidence_id),
  KEY idx_geo_graph_evidence_site_type (site_id, evidence_type),
  KEY idx_geo_graph_evidence_entity (entity_id),
  KEY idx_geo_graph_evidence_edge (edge_id),
  KEY idx_geo_graph_evidence_snapshot (snapshot_id),
  CONSTRAINT fk_geo_graph_evidence_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_graph_evidence_entity FOREIGN KEY (entity_id) REFERENCES geo_graph_entities (entity_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_graph_evidence_edge FOREIGN KEY (edge_id) REFERENCES geo_graph_edges (edge_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_graph_evidence_snapshot FOREIGN KEY (snapshot_id) REFERENCES geo_page_snapshots (snapshot_id) ON DELETE SET NULL,
  CONSTRAINT fk_geo_graph_evidence_url FOREIGN KEY (url_id) REFERENCES geo_urls (url_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点知识图谱证据表，记录实体和关系的来源依据';

CREATE TABLE IF NOT EXISTS geo_site_graph_snapshots (
  graph_snapshot_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图谱快照主键 ID',
  site_id BIGINT UNSIGNED NOT NULL COMMENT '所属站点 ID',
  task_id CHAR(32) DEFAULT NULL COMMENT '触发本次构建的任务 ID',
  graph_version VARCHAR(32) NOT NULL DEFAULT 'site-graph-v1' COMMENT '图谱构建版本号',
  source_snapshot_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '参与构建的页面快照数量',
  entity_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本次图谱实体数量',
  edge_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本次图谱关系边数量',
  evidence_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本次图谱证据数量',
  graph_json LONGTEXT DEFAULT NULL COMMENT '图谱快照 JSON，用于调试和离线分析',
  note TEXT DEFAULT NULL COMMENT '构建备注或异常说明',
  built_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '图谱构建完成时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  PRIMARY KEY (graph_snapshot_id),
  KEY idx_geo_site_graph_snapshots_site_built (site_id, built_at),
  KEY idx_geo_site_graph_snapshots_task (task_id),
  CONSTRAINT fk_geo_site_graph_snapshots_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点知识图谱快照表，记录每次构建结果摘要';

CREATE TABLE IF NOT EXISTS geo_audit_tasks (
  task_id CHAR(32) NOT NULL COMMENT '审计任务 ID',
  site_id BIGINT UNSIGNED DEFAULT NULL COMMENT '任务关联的站点 ID',
  domain VARCHAR(255) NOT NULL COMMENT '任务目标域名',
  task_type VARCHAR(64) NOT NULL COMMENT '任务类型，如 site_geo_audit',
  mode VARCHAR(32) NOT NULL DEFAULT 'standard' COMMENT '审计模式，如 standard、premium',
  status VARCHAR(32) NOT NULL COMMENT '任务状态，如 queued、running、completed、failed',
  cache_key CHAR(64) DEFAULT NULL COMMENT '缓存键哈希',
  url VARCHAR(1024) NOT NULL COMMENT '任务原始 URL',
  normalized_url VARCHAR(1024) NOT NULL COMMENT '任务规范化 URL',
  feedback_lang VARCHAR(8) NOT NULL DEFAULT 'en' COMMENT '反馈语言',
  force_refresh TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否强制刷新缓存与页面快照',
  cached TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否命中了审计缓存',
  full_audit TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否开启 full audit',
  requested_max_pages INT NOT NULL DEFAULT 12 COMMENT '请求的最大页面数',
  result_json LONGTEXT DEFAULT NULL COMMENT '任务完成后的完整结果 JSON',
  error_text TEXT DEFAULT NULL COMMENT '任务失败时的错误文本',
  created_at DATETIME(6) NOT NULL COMMENT '任务创建时间',
  updated_at DATETIME(6) NOT NULL COMMENT '任务更新时间',
  completed_at DATETIME(6) DEFAULT NULL COMMENT '任务完成时间',
  PRIMARY KEY (task_id),
  KEY idx_geo_audit_tasks_domain_created (domain, created_at),
  KEY idx_geo_audit_tasks_site_created (site_id, created_at),
  CONSTRAINT fk_geo_audit_tasks_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='异步审计任务持久化表';
