CREATE TABLE IF NOT EXISTS geo_sites (
  site_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  domain VARCHAR(255) NOT NULL,
  site_root_url VARCHAR(512) NOT NULL,
  scope_root_url VARCHAR(512) NOT NULL,
  scope_key CHAR(64) NOT NULL,
  business_type VARCHAR(64) DEFAULT NULL,
  total_url_count INT UNSIGNED NOT NULL DEFAULT 0,
  snapshot_url_count INT UNSIGNED NOT NULL DEFAULT 0,
  discovery_json LONGTEXT DEFAULT NULL,
  key_pages_json JSON DEFAULT NULL,
  last_discovered_at DATETIME(6) DEFAULT NULL,
  last_snapshot_at DATETIME(6) DEFAULT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (site_id),
  UNIQUE KEY uq_geo_sites_domain_scope (domain, scope_key),
  KEY idx_geo_sites_last_discovered (last_discovered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS geo_urls (
  url_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  site_id BIGINT UNSIGNED NOT NULL,
  normalized_url VARCHAR(1024) NOT NULL,
  url_hash CHAR(64) NOT NULL,
  final_url VARCHAR(1024) DEFAULT NULL,
  url_type VARCHAR(32) NOT NULL DEFAULT 'unknown',
  discovery_source VARCHAR(32) NOT NULL DEFAULT 'unknown',
  priority SMALLINT NOT NULL DEFAULT 0,
  fetch_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_discovered_at DATETIME(6) DEFAULT NULL,
  last_fetched_at DATETIME(6) DEFAULT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (url_id),
  UNIQUE KEY uq_geo_urls_site_hash (site_id, url_hash),
  KEY idx_geo_urls_site_type (site_id, url_type),
  KEY idx_geo_urls_site_source (site_id, discovery_source),
  KEY idx_geo_urls_site_priority (site_id, priority),
  CONSTRAINT fk_geo_urls_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS geo_page_snapshots (
  snapshot_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  site_id BIGINT UNSIGNED NOT NULL,
  url_id BIGINT UNSIGNED NOT NULL,
  normalized_url VARCHAR(1024) NOT NULL,
  final_url VARCHAR(1024) NOT NULL,
  url_type VARCHAR(32) NOT NULL DEFAULT 'unknown',
  fetch_status VARCHAR(32) NOT NULL DEFAULT 'success',
  status_code INT DEFAULT NULL,
  title VARCHAR(512) DEFAULT NULL,
  meta_description TEXT DEFAULT NULL,
  canonical VARCHAR(1024) DEFAULT NULL,
  lang VARCHAR(32) DEFAULT NULL,
  word_count INT NOT NULL DEFAULT 0,
  html_length INT NOT NULL DEFAULT 0,
  text_excerpt TEXT DEFAULT NULL,
  content_hash CHAR(64) DEFAULT NULL,
  page_profile_json LONGTEXT NOT NULL,
  parsed_json LONGTEXT DEFAULT NULL,
  text_content MEDIUMTEXT DEFAULT NULL,
  raw_html MEDIUMTEXT DEFAULT NULL,
  fetched_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (snapshot_id),
  UNIQUE KEY uq_geo_page_snapshots_url (url_id),
  KEY idx_geo_page_snapshots_site (site_id),
  KEY idx_geo_page_snapshots_type (site_id, url_type),
  KEY idx_geo_page_snapshots_fetched_at (fetched_at),
  CONSTRAINT fk_geo_page_snapshots_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE CASCADE,
  CONSTRAINT fk_geo_page_snapshots_url FOREIGN KEY (url_id) REFERENCES geo_urls (url_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS geo_audit_tasks (
  task_id CHAR(32) NOT NULL,
  site_id BIGINT UNSIGNED DEFAULT NULL,
  domain VARCHAR(255) NOT NULL,
  task_type VARCHAR(64) NOT NULL,
  mode VARCHAR(32) NOT NULL DEFAULT 'standard',
  status VARCHAR(32) NOT NULL,
  cache_key CHAR(64) DEFAULT NULL,
  url VARCHAR(1024) NOT NULL,
  normalized_url VARCHAR(1024) NOT NULL,
  feedback_lang VARCHAR(8) NOT NULL DEFAULT 'en',
  force_refresh TINYINT(1) NOT NULL DEFAULT 0,
  cached TINYINT(1) NOT NULL DEFAULT 0,
  full_audit TINYINT(1) NOT NULL DEFAULT 0,
  requested_max_pages INT NOT NULL DEFAULT 12,
  result_json LONGTEXT DEFAULT NULL,
  error_text TEXT DEFAULT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6) DEFAULT NULL,
  PRIMARY KEY (task_id),
  KEY idx_geo_audit_tasks_domain_created (domain, created_at),
  KEY idx_geo_audit_tasks_site_created (site_id, created_at),
  CONSTRAINT fk_geo_audit_tasks_site FOREIGN KEY (site_id) REFERENCES geo_sites (site_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
